# Generated by Django 3.0.14 on 2021-09-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0004_auto_20210902_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='meta',
            field=models.TextField(blank=True),
        ),
    ]
