# Generated by Django 3.0.14 on 2021-10-14 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0008_auto_20211007_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqtext',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Subapp01.FAQCategory'),
        ),
    ]
