# Generated by Django 3.0.14 on 2021-10-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0009_faqtext_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqtext',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
