# Generated by Django 3.0.14 on 2021-12-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0011_emienquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADV_EMI_CAL',
            fields=[
                ('cal_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bank', models.CharField(blank=True, max_length=200)),
                ('loan_type', models.CharField(blank=True, max_length=500)),
                ('feature_type', models.CharField(blank=True, max_length=500)),
                ('gender', models.CharField(blank=True, max_length=500)),
                ('cibil_min', models.IntegerField(blank=True)),
                ('cibil_max', models.IntegerField(blank=True)),
                ('loan_min', models.IntegerField(blank=True)),
                ('loan_max', models.IntegerField(blank=True)),
                ('interest_rate', models.FloatField(blank=True)),
            ],
        ),
    ]
