# Generated by Django 3.0.14 on 2021-12-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0012_adv_emi_cal'),
    ]

    operations = [
        migrations.AddField(
            model_name='emienquiry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
