# Generated by Django 3.0.3 on 2021-12-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0013_emienquiry_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfscData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IFSC_CODE', models.CharField(blank=True, max_length=200)),
                ('BANK', models.CharField(blank=True, max_length=200)),
                ('STATE', models.CharField(blank=True, max_length=200)),
                ('DISTRIC', models.CharField(blank=True, max_length=200)),
                ('CITY', models.CharField(blank=True, max_length=200)),
                ('BRANCH', models.CharField(blank=True, max_length=200)),
                ('PHONE', models.IntegerField(blank=True)),
                ('STD_CODE', models.FloatField(blank=True)),
                ('MICR', models.IntegerField(blank=True)),
                ('ADDRESS', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
