# Generated by Django 3.2.6 on 2022-01-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0014_auto_20211230_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfscData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IFSC_CODE', models.CharField(blank=True, max_length=200, null=True)),
                ('BANK', models.CharField(blank=True, max_length=200, null=True)),
                ('STATE', models.CharField(blank=True, max_length=200, null=True)),
                ('DISTRICT', models.CharField(blank=True, max_length=200, null=True)),
                ('CITY', models.CharField(blank=True, max_length=200)),
                ('BRANCH', models.CharField(blank=True, max_length=200, null=True)),
                ('PHONE', models.FloatField(blank=True, null=True)),
                ('STD_CODE', models.FloatField(blank=True, null=True)),
                ('MICR', models.FloatField(blank=True, null=True)),
                ('ADDRESS', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='city',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='ifscdetails',
            name='bankname',
        ),
        migrations.RemoveField(
            model_name='ifscdetails',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='ifscdetails',
            name='city',
        ),
        migrations.RemoveField(
            model_name='ifscdetails',
            name='service',
        ),
        migrations.RemoveField(
            model_name='ifscdetails',
            name='state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='bankname',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Ifscdetails',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
