# Generated by Django 3.0.3 on 2021-12-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0014_ifscdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ifscdata',
            old_name='DISTRIC',
            new_name='DISTRICT',
        ),
    ]
