# Generated by Django 3.2.6 on 2022-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0015_auto_20211218_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('babk_ifsc', models.CharField(blank=True, max_length=500, null=True)),
                ('Bank', models.CharField(blank=True, max_length=1000, null=True)),
                ('level1', models.CharField(blank=True, max_length=1000, null=True)),
                ('level2', models.CharField(blank=True, max_length=500, null=True)),
                ('level3', models.CharField(blank=True, max_length=500, null=True)),
                ('helpful_link', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EMI_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(blank=True, max_length=200)),
                ('PhoneNumber', models.FloatField(blank=True, null=True)),
                ('PAN', models.CharField(blank=True, max_length=200)),
                ('NetMonthSalary', models.CharField(blank=True, max_length=200)),
                ('LoanAmount', models.CharField(blank=True, max_length=200)),
                ('Tenure', models.CharField(blank=True, max_length=200)),
                ('Bankname', models.CharField(blank=True, max_length=200)),
                ('CreditScore', models.FloatField(blank=True, null=True)),
                ('InterestRate', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ifscdata',
            name='ADDRESS',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ifscdata',
            name='BANK',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ifscdata',
            name='BRANCH',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ifscdata',
            name='DISTRICT',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ifscdata',
            name='IFSC_CODE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ifscdata',
            name='MICR',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ifscdata',
            name='PHONE',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ifscdata',
            name='STATE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ifscdata',
            name='STD_CODE',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
