# Generated by Django 3.0.3 on 2021-12-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0015_auto_20211218_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifscdata',
            name='MICR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ifscdata',
            name='STD_CODE',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
