# Generated by Django 3.2.6 on 2022-02-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0016_auto_20220131_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emi_data',
            old_name='Bankname',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='emi_data',
            old_name='CreditScore',
            new_name='creditscore',
        ),
        migrations.RenameField(
            model_name='emi_data',
            old_name='InterestRate',
            new_name='interest_rate',
        ),
        migrations.RenameField(
            model_name='emi_data',
            old_name='FullName',
            new_name='monthlySalary',
        ),
        migrations.RenameField(
            model_name='emi_data',
            old_name='NetMonthSalary',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='emi_data',
            old_name='PAN',
            new_name='pan',
        ),
        migrations.RenameField(
            model_name='emi_data',
            old_name='PhoneNumber',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='emi_data',
            old_name='Tenure',
            new_name='tenure',
        ),
    ]
