# Generated by Django 3.0.3 on 2021-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0016_auto_20211218_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifscdata',
            name='MICR',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
