# Generated by Django 3.0.3 on 2021-12-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0017_auto_20211218_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifscdata',
            name='PHONE',
            field=models.FloatField(blank=True),
        ),
    ]
