# Generated by Django 3.2.6 on 2022-02-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0018_auto_20220201_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('pan_number', models.CharField(max_length=500)),
                ('emp_type', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('email_address', models.CharField(max_length=500)),
                ('Date_of_birth', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Firstname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='emi_data',
            old_name='interest_rate',
            new_name='loanamount',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Lastname',
        ),
        migrations.AddField(
            model_name='emi_data',
            name='creditscore',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emi_data',
            name='dob',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='emi_data',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='emi_data',
            name='employment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='emi_data',
            name='gender',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='emi_data',
            name='loantype',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='emi_data',
            name='ongoingemi',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emi_data',
            name='salary',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emi_data',
            name='tenure',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
