# Generated by Django 3.0.3 on 2022-01-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0019_auto_20211218_2058'),
        ('Subapp01', '0015_auto_20220103_1232'),
    ]

    operations = [
    ]
