# Generated by Django 3.2.6 on 2022-01-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0019_auto_20211218_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_grievance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_ifsc', models.CharField(blank=True, max_length=500, null=True)),
                ('Bank', models.CharField(blank=True, max_length=1000, null=True)),
                ('level1', models.CharField(blank=True, max_length=1000, null=True)),
                ('level2', models.CharField(blank=True, max_length=500, null=True)),
                ('level3', models.CharField(blank=True, max_length=500, null=True)),
                ('helpful_link', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
