# Generated by Django 3.2.6 on 2022-02-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0020_auto_20220217_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi_data',
            name='creditscore',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
