# Generated by Django 3.2.6 on 2022-02-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0020_auto_20220217_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='emi_data',
            name='creditscore',
        ),
        migrations.AlterField(
            model_name='emi_data',
            name='ongoingemi',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emi_data',
            name='salary',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='emi_data',
            name='tenure',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
