# Generated by Django 3.2.6 on 2022-05-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0021_auto_20220223_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='loan_comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(blank=True, max_length=200)),
                ('min_interest_rate', models.CharField(blank=True, max_length=200)),
                ('max_interest_rate', models.CharField(blank=True, max_length=200)),
                ('processing_fees', models.CharField(blank=True, max_length=200)),
                ('loan_max', models.CharField(blank=True, max_length=200)),
                ('loan_min', models.CharField(blank=True, max_length=200)),
                ('max_tenure', models.CharField(blank=True, max_length=200)),
                ('lowest_emi_per_lakh', models.CharField(blank=True, max_length=200)),
                ('benchmark_rate', models.CharField(blank=True, max_length=200)),
                ('current_mclr_plr', models.CharField(blank=True, max_length=200)),
                ('base_rate', models.CharField(blank=True, max_length=200)),
                ('min_age', models.CharField(blank=True, max_length=200)),
                ('max_age', models.CharField(blank=True, max_length=200)),
                ('for_women', models.CharField(blank=True, max_length=200)),
                ('overdraft_facilty', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
