# Generated by Django 3.2.6 on 2022-05-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Subapp01', '0022_loan_comparison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_comparison',
            name='loan_min',
        ),
    ]
